"""Tests for ``envcore.export``."""

from __future__ import annotations

import pytest

from envcore.export import export, ALL_FORMATS
from envcore.manifest import Manifest


@pytest.fixture()
def sample_manifest() -> Manifest:
    return Manifest(
        packages={"numpy": "1.26.4", "pandas": "2.1.3", "click": "8.1.7"},
        envcore_version="0.1.0",
        python_version="3.11.5",
        platform="test",
        created_at="2026-01-01T00:00:00Z",
    )


class TestExport:
    """Tests for each export format."""

    def test_requirements(self, sample_manifest: Manifest) -> None:
        out = export(sample_manifest, "requirements")
        assert "numpy==1.26.4" in out
        assert "pandas==2.1.3" in out
        assert "click==8.1.7" in out
        assert "Auto-generated by envcore" in out

    def test_pyproject(self, sample_manifest: Manifest) -> None:
        out = export(sample_manifest, "pyproject")
        assert '"numpy==1.26.4"' in out
        assert "[project]" in out
        assert "dependencies" in out

    def test_conda(self, sample_manifest: Manifest) -> None:
        out = export(sample_manifest, "conda")
        assert "conda-forge" in out
        assert "python=3.11.5" in out
        assert "- numpy==1.26.4" in out

    def test_docker(self, sample_manifest: Manifest) -> None:
        out = export(sample_manifest, "docker")
        assert "FROM python:3.11-slim" in out
        assert "numpy==1.26.4" in out
        assert "pip install" in out

    def test_pipfile(self, sample_manifest: Manifest) -> None:
        out = export(sample_manifest, "pipfile")
        assert "[packages]" in out
        assert 'numpy = "==1.26.4"' in out
        assert "[requires]" in out

    def test_setup(self, sample_manifest: Manifest) -> None:
        out = export(sample_manifest, "setup")
        assert "setup(" in out
        assert "install_requires" in out
        assert '"numpy==1.26.4"' in out

    def test_all_formats_produce_output(self, sample_manifest: Manifest) -> None:
        for fmt in ALL_FORMATS:
            out = export(sample_manifest, fmt)
            assert len(out) > 0, f"Format {fmt} produced empty output"

    def test_unknown_format_raises(self, sample_manifest: Manifest) -> None:
        with pytest.raises(ValueError, match="Unknown format"):
            export(sample_manifest, "invalid_format")

    def test_empty_manifest(self) -> None:
        m = Manifest(packages={})
        out = export(m, "requirements")
        assert "Auto-generated" in out

    def test_packages_sorted(self, sample_manifest: Manifest) -> None:
        out = export(sample_manifest, "requirements")
        lines = [l for l in out.strip().split("\n") if "==" in l]
        assert lines == sorted(lines)
