"""
Export manifests to various dependency formats.

Supports: requirements.txt, pyproject.toml, conda environment.yml,
Dockerfile, and Pipfile.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from envcore.manifest import DEFAULT_MANIFEST_PATH, Manifest, load

ExportFormat = Literal[
    "requirements", "pyproject", "conda", "docker", "pipfile", "setup"
]

ALL_FORMATS: list[ExportFormat] = [
    "requirements", "pyproject", "conda", "docker", "pipfile", "setup",
]


def _to_requirements(manifest: Manifest) -> str:
    """Generate ``requirements.txt`` content."""
    lines = [
        f"# Auto-generated by envcore {manifest.envcore_version}",
        f"# Python {manifest.python_version}",
        f"# Created: {manifest.created_at}",
        "",
    ]
    for name, version in sorted(manifest.packages.items()):
        lines.append(f"{name}=={version}")
    return "\n".join(lines) + "\n"


def _to_pyproject(manifest: Manifest) -> str:
    """Generate ``pyproject.toml`` dependencies section."""
    deps = []
    for name, version in sorted(manifest.packages.items()):
        deps.append(f'    "{name}=={version}",')
    deps_str = "\n".join(deps)

    lines = [
        f"# Auto-generated by envcore {manifest.envcore_version}",
        "# Paste this into your pyproject.toml [project] section.",
        "",
        "[project]",
        "dependencies = [",
        deps_str,
        "]",
        "",
    ]
    return "\n".join(lines)


def _to_conda(manifest: Manifest) -> str:
    """Generate ``environment.yml`` content."""
    lines = [
        f"# Auto-generated by envcore {manifest.envcore_version}",
        f"name: envcore-environment",
        f"channels:",
        f"  - defaults",
        f"  - conda-forge",
        f"dependencies:",
        f"  - python={manifest.python_version}",
    ]
    pip_deps = []
    for name, version in sorted(manifest.packages.items()):
        pip_deps.append(f"    - {name}=={version}")

    if pip_deps:
        lines.append("  - pip:")
        lines.extend(pip_deps)
    return "\n".join(lines) + "\n"


def _to_docker(manifest: Manifest) -> str:
    """Generate a minimal ``Dockerfile``."""
    py_major_minor = ".".join(manifest.python_version.split(".")[:2])
    pkg_lines = [
        f"        {name}=={version}"
        for name, version in sorted(manifest.packages.items())
    ]
    pip_installs = " \\\n".join(pkg_lines)

    lines = [
        f"# Auto-generated by envcore {manifest.envcore_version}",
        f"FROM python:{py_major_minor}-slim",
        "",
        "WORKDIR /app",
        "",
        f"RUN pip install --no-cache-dir \\",
        pip_installs,
        "",
        "COPY . .",
        "",
        'CMD ["python", "main.py"]',
        "",
    ]
    return "\n".join(lines)


def _to_pipfile(manifest: Manifest) -> str:
    """Generate ``Pipfile`` content."""
    lines = [
        f"# Auto-generated by envcore {manifest.envcore_version}",
        "",
        "[[source]]",
        'url = "https://pypi.org/simple"',
        'verify_ssl = true',
        'name = "pypi"',
        "",
        "[packages]",
    ]
    for name, version in sorted(manifest.packages.items()):
        lines.append(f'{name} = "=={version}"')
    lines.extend([
        "",
        "[dev-packages]",
        "",
        "[requires]",
        f'python_version = "{".".join(manifest.python_version.split(".")[:2])}"',
    ])
    return "\n".join(lines) + "\n"


def _to_setup(manifest: Manifest) -> str:
    """Generate ``setup.py`` content."""
    deps = ", ".join(
        f'"{name}=={version}"'
        for name, version in sorted(manifest.packages.items())
    )
    lines = [
        f"# Auto-generated by envcore {manifest.envcore_version}",
        "from setuptools import setup",
        "",
        "setup(",
        f"    install_requires=[{deps}],",
        ")",
        "",
    ]
    return "\n".join(lines)


_FORMATTERS: dict[ExportFormat, callable] = {
    "requirements": _to_requirements,
    "pyproject": _to_pyproject,
    "conda": _to_conda,
    "docker": _to_docker,
    "pipfile": _to_pipfile,
    "setup": _to_setup,
}

_DEFAULT_FILENAMES: dict[ExportFormat, str] = {
    "requirements": "requirements.txt",
    "pyproject": "pyproject_deps.toml",
    "conda": "environment.yml",
    "docker": "Dockerfile",
    "pipfile": "Pipfile",
    "setup": "setup.py",
}


def export(
    manifest: Manifest,
    fmt: ExportFormat,
) -> str:
    """Export a manifest to the given format string.

    Parameters
    ----------
    manifest:
        The manifest to export.
    fmt:
        Target format name.

    Returns
    -------
    str
        The formatted output as a string.
    """
    formatter = _FORMATTERS.get(fmt)
    if formatter is None:
        raise ValueError(f"Unknown format: {fmt!r}. Choose from: {list(_FORMATTERS)}")
    return formatter(manifest)


def export_to_file(
    manifest: Manifest,
    fmt: ExportFormat,
    path: str | Path | None = None,
) -> Path:
    """Export a manifest to a file.

    If *path* is ``None``, a sensible default filename is chosen.

    Returns the path that was written.
    """
    content = export(manifest, fmt)
    dest = Path(path) if path else Path(_DEFAULT_FILENAMES[fmt])
    dest.write_text(content)
    return dest
